ann2srt - 引入原版 v0.3.1 變更
Signed-off-by: Ｖ字龍(Vdragon) <pika1021@gmail.com>

diff --git a/ann2srt b/ann2srt
--- a/ann2srt
+++ b/ann2srt
@@ -6,58 +6,60 @@
 # License: GPL v3
 #
 
-function usage() {
-echo -e "Usage:\n"
-echo -e "\t$(basename "$0") ANNOTATION_FILE\n"
-}
-
-function parseXML() {
-cat "${ANN}" |xmlstarlet sel -t -m 'document/annotations/annotation' -v 'TEXT' -o ',' -m 'segment/movingRegion/rectRegion' -v '@t' -o ',' -b -n
-}
-
-function reformatTime() {
-local H=$(echo "$1" |cut -d ':' -f 1)
-local M=$(echo "$1" |cut -d ':' -f 2)
-local S=$(echo "$1" |cut -d ':' -f 3)
-printf '%02d:%02d:%06.3f' ${H} ${M} ${S} |tr '.' ','
-}
-
-function time2sod() {
-# Convert time in HH:MM:SS.SSS format into second-of-the-day value
-local SOD=$(echo "$1" | awk -F ":" '{printf("%f\n", "$1"*3600+$2*60+$3);}')
-
-echo ${SOD}
-}
-
 ANN="$1"
 SRT="$(basename "${ANN}" .xml).srt"
 IFS=$'\n'
 I=0
 
+function usage() {
+	echo -e "Usage:\n"
+	echo -e "\t$(basename "$0") ANNOTATION_FILE\n"
+}
+
+function parseXML() {
+	cat "${ANN}" | tr -d '\r' | tr '\n' ' ' | xmlstarlet sel -t -m 'document/annotations/annotation' -v 'TEXT' -o '|' -m 'segment/movingRegion/rectRegion' -v '@t' -o '|' -b -n | tr -d '\r'
+}
+
+function reformatTime() {
+	local H=$(echo "$1" |cut -d ':' -f 1)
+	local M=$(echo "$1" |cut -d ':' -f 2)
+	local S=$(echo "$1" |cut -d ':' -f 3)
+	printf '%02d:%02d:%06.3f' ${H} ${M} ${S} |tr '.' ','
+}
+
+function time2sod() {
+	# Convert time in HH:MM:SS.SSS format into second-of-the-day value
+	local SOD=$(echo "$1" | awk -F ":" '{printf("%f\n", "$1"*3600+$2*60+$3);}')
+
+	echo ${SOD}
+}
+
 [ "x${ANN}" = "x" ] && { usage; exit 1; }
 [ -f "${ANN}" ] || { usage; exit 1; }
 [ -f "${SRT}" ] && rm "${SRT}"
-[ -f "${SRT}".tmp ] && rm "${SRT}".tmp
+[ -f "${SRT}.tmp" ] && rm "${SRT}.tmp"
 
 for LINE in $(parseXML); do
-C=$(echo ${LINE} |cut -d ',' -f 1)
-B=$(echo ${LINE} |cut -d ',' -f 2)
-E=$(echo ${LINE} |cut -d ',' -f 3)
-echo "$(time2sod ${B})#${B}#${E}#${C}" >> "${SRT}".tmp
+	C=$(echo ${LINE} |cut -d '|' -f 1)
+	B=$(echo ${LINE} |cut -d '|' -f 2)
+	E=$(echo ${LINE} |cut -d '|' -f 3)
+	echo "$(time2sod ${B})#${B}#${E}#${C}" >> "${SRT}".tmp
 done
 
-grep "###" "${SRT}".tmp && {
-echo "\"${ANN}\" has no valid annotation!"
-rm "${SRT}".tmp
-exit 1
+grep -q "###" "${SRT}.tmp" && { 
+	COUNT=$(grep -c "###" "${SRT}.tmp")
+	echo "[WARNING] \"${ANN}\" contains ${COUNT} invalid annotation(s)! Ignored." >&2
+	mv "${SRT}.tmp" "${SRT}.tmp2"
+	cat "${SRT}.tmp2" | grep -v "###" > "${SRT}.tmp"
+	rm "${SRT}.tmp2"
 }
 
-for LINE in $(cat "${SRT}".tmp|sort -n -t '#'); do
-(( I++ ))
-C=$(echo ${LINE} |cut -d '#' -f 4)
-B=$(reformatTime $(echo ${LINE} |cut -d '#' -f 2))
-E=$(reformatTime $(echo ${LINE} |cut -d '#' -f 3))
-echo -e "${I}\n${B} --> ${E}\n${C}\n" >> "${SRT}"
+for LINE in $(cat "${SRT}.tmp" | sort -n -t '#'); do
+	(( I++ ))
+	C=$(echo ${LINE} | cut -d '#' -f 4)
+	B=$(reformatTime $(echo ${LINE} | cut -d '#' -f 2))
+	E=$(reformatTime $(echo ${LINE} | cut -d '#' -f 3))
+	echo -e "${I}\n${B} --> ${E}\n${C}\n" >> "${SRT}"
 done
 
-rm "${SRT}".tmp
+rm "${SRT}.tmp"
